### ISSUE TITLE
Could you post a demo for uploading files to the API?

### ISSUE THREAD

**Issue by dnutiu** [jwelker110/file-input-accessor#1]
I'm not exactly sure how to upload files to my API using the application/x-www-form-urlencoded content type.

**Comment by jwelker110** [comment]
@dnutiu Thanks for the suggestion. I'll work on getting an example added. In the mean time, I found a couple examples [here](http://javasampleapproach.com/frontend/angular/angular-4-uploadget-multipartfile-tofrom-spring-boot-server#22_Upload_File_Service) and [here](https://stackoverflow.com/questions/47936183/angular-5-file-upload) that may help you move in the right direction.

**Comment by dnutiu** [comment]
Hello, thanks for the quickly response! I have tested the following code and I can confirm that it works.

```
  public submitPaper(receivedData: any, fileList: any): Observable<HttpEvent<any>> {
    const formData = new FormData();
    formData.append('title', receivedData && receivedData.title || null);
    formData.append('description', receivedData && receivedData.description || null);
    formData.append('authors', receivedData && receivedData.authors || null);
    formData.append('manuscript', fileList && fileList['manuscript']);
    formData.append('cover_letter', fileList && fileList['cover_letter']);
    if (formData.get('supplementary_materials') != null) {
      formData.append('supplementary_materials', fileList && fileList['supplementary_materials']);
    }

    const options = {
      headers: this.headers,
      reportProgress: true,
    };

    const req = new HttpRequest('POST', this.apiUrl, formData, options);
    return this.http.request(req);
  }
```

It was the first time I've attempted to upload files via Angular and I got a bit lost there.

**Comment by jwelker110** [comment]
@dnutiu glad you got everything working!

I added an [example](https://github.com/jwelker110/file-input-accessor/blob/master/README.md#uploading-the-files) using [HttpClient](https://v4.angular.io/api/common/http/HttpClient).

**Comment by dnutiu** [comment]
Thank you!
