### ISSUE TITLE
Angular 13 update?

### ISSUE THREAD

**Issue by karptonite** [jwelker110/file-input-accessor#22]
Hey, I know that this isn't a super-active package, but if you can do an angular 13 update, that would be helpful!
At the very least, this still seems to compile OK for Angular 13, so hopefully upgrading won't involve major changes.

**Comment by jwelker110** [comment]
Hi! Thank you for taking the time to bring this to my attention. I did not intend to let this package get out of date like this 😢 

I updated the package. Thank you for using it, I hope it continues to provide what you need.

Again, thanks for taking the time to reach out, I appreciate it.
