### ISSUE TITLE
Angular 14 Update

### ISSUE THREAD

**Issue by karptonite** [jwelker110/file-input-accessor#28]
It is that time again!

This time, an upgrade might be kind of complicated, because of the overhaul to FormControl, unfortunately. I haven't looked into the details yet, but FormControl is now typed. You might be able to get away with just changing your use of `FormControl` to `UntypedFormControl`.

**Comment by jwelker110** [comment]
Ahhh yep sounds like I'll need to figure it all out. Thanks for the heads up! Will plan on updating this within the next day or two!

**Comment by jwelker110** [comment]
Apologies, I kept putting this off and then forgetting about it until today. Latest version has been updated. The control is using UntypedFormControl at the moment. I plan to get that typed but wanted to at least update this version to latest Angular for now. 

Thank you for your patience!
