### ISSUE TITLE
Could you add minWidth/minHeight validators for images

### ISSUE THREAD

**Issue by dzmitrymishyn** [jwelker110/file-input-accessor#4]
It's great library for me, but I have one unresolved issue: I have to validate minWidth for the images that a user uploads.

Are you planning to add these validators in your library?

**Comment by jwelker110** [comment]
Welcome @DmitryMishin !

I'm not sure why I never thought about adding minWidth / minHeight validation when I was adding the max validation. I added minWidth / minHeight validation (just now) and pushed a new version of the package out (8.1.1). 

It works similarly to the [existing](https://github.com/jwelker110/file-input-accessor#validation) maxWidth / maxHeight.

Thank you for taking the time to point out what was missing! I appreciate it.
