### ISSUE TITLE
Single file field

### ISSUE THREAD

**Issue by yamaha252** [jwelker110/file-input-accessor#5]
Hey! Thanks for the awesome lib. It's really helpful!

I can't understand why if I have a single file input field (without `muiltiple` attribute) I have an array of files in the result? Wha't the logic?

```
<input type="file" name="imageFront" [(ngModel)]="imageFront">
```

`[File]` in the result

**Comment by jwelker110** [comment]
I'm glad you are finding this helpful. 

HTML file input provides a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) for single and multiple files. Accessing the file from a FileList that only contains one File still requires using an index.

I wanted to follow the same idea, so the file input accessor emits a list of files even when there is no `multiple` attribute.

Hopefully this makes sense. If not, I'm open to your suggestions on ways to improve the accessor!

**Comment by yamaha252** [comment]
Thanks for your explanation! I've seen that in the sources.
It's correct way if we're talking about browser element api, but that's a directive in the lib which just provides a value to the model and the value type can be different, depends of options.
For example we can look to the behaviour of angular implementation of the select directive. If there is a `multiple` attribute, the value of the model is an array but without `multiple` the value is just a string (or the other type of an option element value). 

I can suggest respecting the `multiple` attribute and without it the directive could provide just the first `File` element from `event.target.files`, but it's breaking changes and I don't know how it's possible or not.

**Comment by jwelker110** [comment]
I think that you have found one of the reasons the Angular team decided not to implement a control value accessor for file inputs and leave it up to the consumers to decide on their own implementation 😄 

The Angular documentation related to the select directive consists of two separate control accessors, one for [multiple](https://angular.io/api/forms/SelectMultipleControlValueAccessor) as well as one for a [single](https://angular.io/api/forms/SelectControlValueAccessor). 

I prefer to maintain one set of code and one set of validators for the file input while keeping the API consistent. This means emitting a list 100% of the time. That keeps the implementation predictable and easier to maintain overall.

I appreciate the feedback, I took some time considering the options and I think it's best to keep the current implementation.

Thank you for taking the time to provide constructive feedback, I appreciate it.
