### ISSUE TITLE
Incorrect peer dependency in package

### ISSUE THREAD

**Issue by karptonite** [jwelker110/file-input-accessor#9]
When I install version 9.0 with yarn, I get the error:
```
warning " > file-input-accessor@9.0.0" has incorrect peer dependency "@angular/common@^8.0.0".
warning " > file-input-accessor@9.0.0" has incorrect peer dependency "@angular/core@^8.0.0".
```

When I look at the `package.json` in the installed package, the `peerDependencies` do appear to be wrong. 

Thanks for a great package!

**Comment by jwelker110** [comment]
Good catch! Thank you for taking the time to reach out. I have updated the peer dependencies.
